travis:
  secure:
    BINSTAR_TOKEN: yNtsiw+9FjLcD2taiSG+0E0C86PRqm+j4HsoMhekp10m9nf3Mj0q5Qm1eQjPTls6aCFI7+1ZqT5kDe4KaFY1jJG4oYbdGG/VEDL//11KQfe16NS9RhU1cBb9B0YPXvzQtlZSC/IhOrSmig9hIasn3CAE1CxFhjqeAUQjlq6+Yzav22vdRdMU+gsgxew4auPJPzYdU9cgLadEgJuuahdtUZVHTnamprOG8K2PQ5ZFHwhR34tptNwENBpa1N/URL2mZji5Zkf5PM8vTD3TcoCPC+wh0FQqGWiiBf8JdqZBHxblSinQVvW6dStWZZxa0oSLSet8EY/UVWYmBmdM4O5fzpSjDU37TQPQ390tlHL4g7ZlSpO1nkBjjBwOuyd9bTE0Qp+V07qzHr9g6c8zBuFFw+nLt5lfAXQJTPPMLPxdsKO35cetbuiNGYAjP8g3vNzYWcaLIvmhX/Mb1PSx83qPJN1LujA59ku1KhJGPdlPQqcMcTORjTc2XnJY1zHCbiLqpiaBx+WQrRn9tUnB1fdGpE/STU1Xv+3RlH+NHJx6gfGc3maWBRhhrC2ESIsp44mY1bfTfDyMZf09pk90uLfQ7bruly+UhByR2su+8RgQB4Uz2P82E3hXczeeDSoLFM2cdFGy90iJZ8qecS7KtOOLpsU1muUjofewIUh8CvceIUA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
